// Code generated by hertz generator.

package core_api

import (
	"context"
	"github.com/xh-polaris/platform-core-api/biz/adaptor"
	"github.com/xh-polaris/platform-core-api/provider"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	core_api "github.com/xh-polaris/platform-core-api/biz/application/dto/platform/core_api"
)

// ReportEvent .
// @router /platform/report_event [POST]
func ReportEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ReportEventRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.DataService.ReportEvent(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
