// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	core_api "platform-core-api/biz/adaptor/router/core_api"
	data "platform-core-api/biz/adaptor/router/data"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	core_api.Register(r)

	data.Register(r)

}
