// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/platform-core-api/biz/application/service"
	"github.com/xh-polaris/platform-core-api/biz/infra/config"
	"github.com/xh-polaris/platform-core-api/biz/infra/rpc/platform_data"
	"github.com/xh-polaris/platform-core-api/biz/infra/rpc/platform_sts"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	client := platform_data.NewPlatformData(configConfig)
	platformData := platform_data.PlatformData{
		Client: client,
	}
	dataService := &service.DataService{
		Config:       configConfig,
		PlatformData: platformData,
	}
	stsserviceClient := platform_sts.NewPlatformSts(configConfig)
	platformSts := &platform_sts.PlatformSts{
		Client: stsserviceClient,
	}
	authService := &service.AuthService{
		Config: configConfig,
		Sts:    platformSts,
	}
	providerProvider := &Provider{
		Config:      configConfig,
		DataService: dataService,
		AuthService: authService,
	}
	return providerProvider, nil
}
