// Code generated by hertz generator.

package core_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _platformMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _reporteventMw() []app.HandlerFunc {
	// your code...
	return nil
}
